services:
  - type: web
    name: rag-flask-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
